command:
  name: redirect
  description: Write the redirects urls in an specified excel file to the target file
  definitions:
    - name: sources
      alias: s
      type: String
      multiple: true
      description: The source file for redirect configurations.
      typeLabel: <file>

    - name: target
      alias: t
      type: String
      description: The target file for the configuration outputs.
      typeLabel: <file>

    - name: base-url
      alias: B
      type: String
      description: The base url.

    - name: prefixes
      alias: P
      type: String
      description: The prefixes for the url, for example the languages. The items should be separated with comma, e.x "en, de, fr".

    - name: check
      alias: C
      type: Boolean
      defaultValue: false
      description: Check the redirect settings

    - name: ignore-lines
      alias: i
      type: String
      description: The lines that should be ignored in the excel file. The items should be separated with comma, e.x "1, 3, 5".

    - name: extra-args
      alias: e
      type: String
      description: Set addtional parameters. Used by check mode to set the addtional http(s) options, e.x. the basic authentication

  usageContents:
    - header: 'Node Tools Application: nginx redirect'
      content: 'Generate redirect configuration from excel file'

    - header: 'Usage'
      content: 'ts-node src/index.ts nginx redirect <options>'

    - header: 'Command options'
      optionsListGenerator: CommandDefinitions
