command:
  name: redirect
  description: Write the redirects urls in an specified excel file to the target file
  definitions:
    - name: sources
      alias: s
      type: String
      multiple: true
      description: The source file for redirect configurations.
      typeLabel: <file>

    - name: target
      alias: t
      type: String
      description: The target file for the configuration outputs.
      typeLabel: <file>

    - name: base-url
      alias: B
      type: String
      description: The base url.

    - name: prefixes
      alias: P
      type: String
      description: The prefixes for the url, for example the languages. The items should be separated with comma, e.x "en, de, fr".

  usageContents:
    - header: 'Node Tools Application: nginx redirect'
      content: 'Generate redirect configuration from excel file'

    - header: 'Usage'
      content: 'ts-node src/index.ts nginx redirect <options>'

    - header: 'Command options'
      optionsListGenerator: CommandDefinitions
