command:
  name: nginx
  description: Execute an automation job for nginx.

  definitions:
    - name: command
      defaultOption: true
      hideInHelp: true

    - name: help
      alias: h
      type: Boolean
      defaultValue: false
      description: Show the help content of the given command.

  subCommands:
    includes:
      files:
        - nginx/redirectCommand.yml

  usageContents:
    - header: 'Node Tools Application: nginx'
      content: 'Execute an automation job for nginx.'

    - header: 'Usage'
      content: 'ts-node src/index.ts nginx <command> <options>'

    - header: 'Command List'
      contentGernerator: UsageContentsForCommands

    - header: 'Command options'
      optionsListGenerator: CommandDefinitions

    - header: 'Show help information of a command'
      content: 'ts-node src/index.ts nginx -h <command>'
